// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/book.dart';
import 'data/models/chat_message.dart';
import 'data/models/page_data.dart';
import 'data/models/reading_session.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6379865091478220324),
    name: 'Book',
    lastPropertyId: const obx_int.IdUid(9, 6023182140359671564),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 515549750306017101),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4926085433341750152),
        name: 'filePath',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 2784645128045631049),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1106043298823627422),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4408829355877209968),
        name: 'coverPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7036169830253348798),
        name: 'fileHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8952857611856345339),
        name: 'lastReadPage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6280387640446049340),
        name: 'totalPages',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6548015145740235673),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6023182140359671564),
        name: 'lastOpened',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'pageData',
        srcEntity: 'PageData',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4222401676141091067),
    name: 'ChatMessage',
    lastPropertyId: const obx_int.IdUid(6, 4238803759383350656),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5032687394109443125),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 160554495877423594),
        name: 'isUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5208234107525870656),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7356188830262425925),
        name: 'pageDataId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 128695747907237997),
        relationField: 'pageData',
        relationTarget: 'PageData',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4238803759383350656),
        name: 'text',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2777067846752820301),
    name: 'PageData',
    lastPropertyId: const obx_int.IdUid(6, 8220424342842555514),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1591640035521152472),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4609370686826265008),
        name: 'pageIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 942070055569246865),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 844172460129893956),
        name: 'screenshotPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5091198670677293746),
        name: 'bookId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 6805188514825111571),
        relationField: 'book',
        relationTarget: 'Book',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8220424342842555514),
        name: 'profileId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'messages',
        srcEntity: 'ChatMessage',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3026563595357886774),
    name: 'ReadingSession',
    lastPropertyId: const obx_int.IdUid(5, 6959346952928767394),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1393331994838598114),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1076564017031954779),
        name: 'startTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8698210113277131770),
        name: 'endTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5035777397454395313),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6959346952928767394),
        name: 'bookId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 7650041253252762183),
        relationField: 'book',
        relationTarget: 'Book',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 3026563595357886774),
    lastIndexId: const obx_int.IdUid(4, 7650041253252762183),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [7355032082823092564],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Book: obx_int.EntityDefinition<Book>(
      model: _entities[0],
      toOneRelations: (Book object) => [],
      toManyRelations: (Book object) => {
        obx_int.RelInfo<PageData>.toOneBacklink(
          5,
          object.id,
          (PageData srcObject) => srcObject.book,
        ): object.pageData,
      },
      getId: (Book object) => object.id,
      setId: (Book object, int id) {
        object.id = id;
      },
      objectToFB: (Book object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final titleOffset = fbb.writeString(object.title);
        final coverPathOffset = object.coverPath == null
            ? null
            : fbb.writeString(object.coverPath!);
        final fileHashOffset = fbb.writeString(object.fileHash);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, filePathOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, coverPathOffset);
        fbb.addOffset(4, fileHashOffset);
        fbb.addInt64(5, object.lastReadPage);
        fbb.addInt64(6, object.totalPages);
        fbb.addInt64(7, object.addedAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.lastOpened.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final fileHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final coverPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final lastReadPageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final totalPagesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final lastOpenedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = Book(
          filePath: filePathParam,
          title: titleParam,
          fileHash: fileHashParam,
          coverPath: coverPathParam,
          lastReadPage: lastReadPageParam,
          totalPages: totalPagesParam,
          addedAt: addedAtParam,
          lastOpened: lastOpenedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<Book>(
          object.pageData,
          store,
          obx_int.RelInfo<PageData>.toOneBacklink(
            5,
            object.id,
            (PageData srcObject) => srcObject.book,
          ),
        );
        return object;
      },
    ),
    ChatMessage: obx_int.EntityDefinition<ChatMessage>(
      model: _entities[1],
      toOneRelations: (ChatMessage object) => [object.pageData],
      toManyRelations: (ChatMessage object) => {},
      getId: (ChatMessage object) => object.id,
      setId: (ChatMessage object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessage object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addBool(2, object.isUser);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(4, object.pageData.targetId);
        fbb.addOffset(5, textOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final isUserParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = ChatMessage(
          text: textParam,
          isUser: isUserParam,
          timestamp: timestampParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.pageData.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.pageData.attach(store);
        return object;
      },
    ),
    PageData: obx_int.EntityDefinition<PageData>(
      model: _entities[2],
      toOneRelations: (PageData object) => [object.book],
      toManyRelations: (PageData object) => {
        obx_int.RelInfo<ChatMessage>.toOneBacklink(
          5,
          object.id,
          (ChatMessage srcObject) => srcObject.pageData,
        ): object.messages,
      },
      getId: (PageData object) => object.id,
      setId: (PageData object, int id) {
        object.id = id;
      },
      objectToFB: (PageData object, fb.Builder fbb) {
        final summaryOffset = object.summary == null
            ? null
            : fbb.writeString(object.summary!);
        final screenshotPathOffset = object.screenshotPath == null
            ? null
            : fbb.writeString(object.screenshotPath!);
        final profileIdOffset = fbb.writeString(object.profileId);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pageIndex);
        fbb.addOffset(2, summaryOffset);
        fbb.addOffset(3, screenshotPathOffset);
        fbb.addInt64(4, object.book.targetId);
        fbb.addOffset(5, profileIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final pageIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final profileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final screenshotPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = PageData(
          pageIndex: pageIndexParam,
          profileId: profileIdParam,
          summary: summaryParam,
          screenshotPath: screenshotPathParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.book.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.book.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<PageData>(
          object.messages,
          store,
          obx_int.RelInfo<ChatMessage>.toOneBacklink(
            5,
            object.id,
            (ChatMessage srcObject) => srcObject.pageData,
          ),
        );
        return object;
      },
    ),
    ReadingSession: obx_int.EntityDefinition<ReadingSession>(
      model: _entities[3],
      toOneRelations: (ReadingSession object) => [object.book],
      toManyRelations: (ReadingSession object) => {},
      getId: (ReadingSession object) => object.id,
      setId: (ReadingSession object, int id) {
        object.id = id;
      },
      objectToFB: (ReadingSession object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.startTime.millisecondsSinceEpoch);
        fbb.addInt64(2, object.endTime?.millisecondsSinceEpoch);
        fbb.addInt64(3, object.duration);
        fbb.addInt64(4, object.book.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final endTimeParam = endTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endTimeValue);
        final durationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = ReadingSession(
          startTime: startTimeParam,
          endTime: endTimeParam,
          duration: durationParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.book.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.book.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Book] entity fields to define ObjectBox queries.
class Book_ {
  /// See [Book.id].
  static final id = obx.QueryIntegerProperty<Book>(_entities[0].properties[0]);

  /// See [Book.filePath].
  static final filePath = obx.QueryStringProperty<Book>(
    _entities[0].properties[1],
  );

  /// See [Book.title].
  static final title = obx.QueryStringProperty<Book>(
    _entities[0].properties[2],
  );

  /// See [Book.coverPath].
  static final coverPath = obx.QueryStringProperty<Book>(
    _entities[0].properties[3],
  );

  /// See [Book.fileHash].
  static final fileHash = obx.QueryStringProperty<Book>(
    _entities[0].properties[4],
  );

  /// See [Book.lastReadPage].
  static final lastReadPage = obx.QueryIntegerProperty<Book>(
    _entities[0].properties[5],
  );

  /// See [Book.totalPages].
  static final totalPages = obx.QueryIntegerProperty<Book>(
    _entities[0].properties[6],
  );

  /// See [Book.addedAt].
  static final addedAt = obx.QueryDateProperty<Book>(
    _entities[0].properties[7],
  );

  /// See [Book.lastOpened].
  static final lastOpened = obx.QueryDateProperty<Book>(
    _entities[0].properties[8],
  );

  /// see [Book.pageData]
  static final pageData = obx.QueryBacklinkToMany<PageData, Book>(
    PageData_.book,
  );
}

/// [ChatMessage] entity fields to define ObjectBox queries.
class ChatMessage_ {
  /// See [ChatMessage.id].
  static final id = obx.QueryIntegerProperty<ChatMessage>(
    _entities[1].properties[0],
  );

  /// See [ChatMessage.isUser].
  static final isUser = obx.QueryBooleanProperty<ChatMessage>(
    _entities[1].properties[1],
  );

  /// See [ChatMessage.timestamp].
  static final timestamp = obx.QueryDateProperty<ChatMessage>(
    _entities[1].properties[2],
  );

  /// See [ChatMessage.pageData].
  static final pageData = obx.QueryRelationToOne<ChatMessage, PageData>(
    _entities[1].properties[3],
  );

  /// See [ChatMessage.text].
  static final text = obx.QueryStringProperty<ChatMessage>(
    _entities[1].properties[4],
  );
}

/// [PageData] entity fields to define ObjectBox queries.
class PageData_ {
  /// See [PageData.id].
  static final id = obx.QueryIntegerProperty<PageData>(
    _entities[2].properties[0],
  );

  /// See [PageData.pageIndex].
  static final pageIndex = obx.QueryIntegerProperty<PageData>(
    _entities[2].properties[1],
  );

  /// See [PageData.summary].
  static final summary = obx.QueryStringProperty<PageData>(
    _entities[2].properties[2],
  );

  /// See [PageData.screenshotPath].
  static final screenshotPath = obx.QueryStringProperty<PageData>(
    _entities[2].properties[3],
  );

  /// See [PageData.book].
  static final book = obx.QueryRelationToOne<PageData, Book>(
    _entities[2].properties[4],
  );

  /// See [PageData.profileId].
  static final profileId = obx.QueryStringProperty<PageData>(
    _entities[2].properties[5],
  );

  /// see [PageData.messages]
  static final messages = obx.QueryBacklinkToMany<ChatMessage, PageData>(
    ChatMessage_.pageData,
  );
}

/// [ReadingSession] entity fields to define ObjectBox queries.
class ReadingSession_ {
  /// See [ReadingSession.id].
  static final id = obx.QueryIntegerProperty<ReadingSession>(
    _entities[3].properties[0],
  );

  /// See [ReadingSession.startTime].
  static final startTime = obx.QueryDateProperty<ReadingSession>(
    _entities[3].properties[1],
  );

  /// See [ReadingSession.endTime].
  static final endTime = obx.QueryDateProperty<ReadingSession>(
    _entities[3].properties[2],
  );

  /// See [ReadingSession.duration].
  static final duration = obx.QueryIntegerProperty<ReadingSession>(
    _entities[3].properties[3],
  );

  /// See [ReadingSession.book].
  static final book = obx.QueryRelationToOne<ReadingSession, Book>(
    _entities[3].properties[4],
  );
}
